### PR TITLE
Add conr.ad

### PR DESCRIPTION
**Pull request by yuvadm**
Hey @conraddecker, would you like to merge this PR adding you to https://namehack.club?

### CODE REVIEW

**Comment by conraddecker** [comment]
Hey @yuvadm, sure thing, that would be rad. I appreciate it :)

**Comment by yuvadm** [comment]
@conraddecker - cool! Would you like to provide a title for yourself?

**Comment by conraddecker** [comment]
Nothing for the time being :) If I think of something, it looks like you accept PRs?

**Comment by conraddecker** [comment]
Actually, if you want to include “Digital Creator & Technologist” for me - that should sum it up pretty well. Cheers!

**Comment by yuvadm** [comment]
Awesome, welcome to the club! :rocket: Note that I added `http://conr.ad` as your URL since it seems your HTTPS endpoint is timing out. Feel free to open a PR once it's fixed.

**Comment by conraddecker** [comment]
Ah nice, thanks for the heads up. I'll get that fixed and open a PR when it's ready.

**Pull request merged**
