### PR TITLE
Add jor.ge

### PR DESCRIPTION
**Pull request by yuvadm**
Hey @jvidal-sysadmin, would you like to merge this PR adding you to https://namehack.club?

### CODE REVIEW

**Comment by jvidal-sysadmin** [comment]
wtf xDDDDD

Let me think about it along this weekend please :D

**Comment by jvidal-sysadmin** [comment]
Enough thinking, we gonna do it. I'm in :)

**Comment by yuvadm** [comment]
You got it :rofl: should I add a `title`?

**Comment by jvidal-sysadmin** [comment]
"DevOps, infrastructure architect, custom keyboards builder."

**Comment by yuvadm** [comment]
Done, welcome to the club :partying_face:

**Pull request merged**
