### PR TITLE
Add nit.ai

### PR DESCRIPTION
**Pull request by selfish**
Awesome project.
Alternate PR to #50 - adding a title.

### CODE REVIEW

**Comment by yuvadm** [comment]
Aww yiss :partying_face: welcome to the club!

**Comment by selfish** [comment]
> Aww yiss 🥳 welcome to the club!

Ty ty @yuvadm
BTW, would you mind sharing how you trace potential members? I'm intrigued.

**Comment by yuvadm** [comment]
Secret sauce :wink: I did an initial batch using the `scan.py` script that pulled a list of English names and checked for active homepages. I think I got most of those down and automated the process for opening PRs.

Getting coverage over larger lists of international names is still TBD, if you have any ideas I'd love to hear them!

**Comment by selfish** [comment]
Well done.
I'll ping you if I have any thoughts.
This idea deserves some publicity. Maybe even something producthunt-y.

Thanks for including me!

**Comment by yuvadm** [comment]
Well, you've included yourself by having an awesome domain name, I had nothing to do with that :)

As for publicity, I'm definitely open to start posting this places once there's an initial mass of members, and possibly a less MVP-ish design.

**Pull request merged**
