### PR TITLE
Add ar.al

### PR DESCRIPTION
**Pull request by yuvadm**
Hey @aral, would you like to merge this PR adding you to https://namehack.club?

### CODE REVIEW

**Comment by aral** [comment]
Haha, I’m not a huge fan of exclusive clubs but, sure, go ahead :) (Beyond the fun, there’s also an important point about identity on the Internet being made.)

**Comment by yuvadm** [comment]
@aral couldn't agree more :) should I add a `title` for your name?

**Comment by aral** [comment]
Sure, how about: “Makes small things.”

Aral

👋🤓 ar.al <https://ar.al> @ Small Technology Foundation <https://small-
tech.org>

On November 17, 2022, GitHub ***@***.***> wrote:
> @aral <https://github.com/aral> couldn't agree more :) should I add a
> title for your name?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/yuvadm/namehack.club/pull/53#issuecomment-
1318607035>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAKGRUD2UOUTMVFYYCG7ATWIYUVLANCNFSM6AAAAAASDCBUJY>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by yuvadm** [comment]
Done, welcome to the club! And thanks for everything you are doing to make the web a nicer place :heart:

**Comment by aral** [comment]
Thank you for the kind words 💕

**Pull request merged**
