### PR TITLE
Add ped.ro

### PR DESCRIPTION
**Pull request by yuvadm**
Hey @peduarte, would you like to merge this PR adding you to https://namehack.club?

### CODE REVIEW

**Comment by peduarte** [comment]
Nice idea :)

**Comment by peduarte** [comment]
You can merge it, thanks!

**Comment by yuvadm** [comment]
should I add a `title`?

**Comment by peduarte** [comment]
Not sure whats the expected structure. Do you need a `title`? Whats it for?

**Comment by yuvadm** [comment]
It's just a line of text (up to 80 chars) that describes you, totally optional

**Comment by yuvadm** [comment]
Done, welcome to the club :rocket:

**Pull request merged**
