### PR TITLE
Add marceli.no

### PR DESCRIPTION
**Pull request by yuvadm**
Hey @m-a-r-c-e-l-i-n-o, would you like to merge this PR adding you to https://namehack.club?

### CODE REVIEW

**Comment by m-a-r-c-e-l-i-n-o** [comment]
Oh, this is funny. Sure, I'm happy to join!

**Comment by m-a-r-c-e-l-i-n-o** [comment]
Feel free to merge :)

**Comment by yuvadm** [comment]
Cool! Should I add a `title`?

**Comment by m-a-r-c-e-l-i-n-o** [comment]
```
Yes, please write: Fullstack architect & dev w/ far too much experience in NodeJS & React.

Looking forward to seeing how large this group can get! 
```

I'm sorry, I was browsing the other titles and accidentally posted on the wrong PR... Thanks for correcting and getting this in.  I appreciate it :)

**Pull request merged**
