### PR TITLE
Add trav.is

### PR DESCRIPTION
**Pull request by yuvadm**
Hey @travismorton, would you like to merge this PR adding you to https://namehack.club?

### CODE REVIEW

**Comment by travismorton** [comment]
Sure thing! Go for it

**Comment by yuvadm** [comment]
Aweosme, should I add a `title`?

**Comment by travismorton** [comment]
Sure, how about "Machine Learning Engineer and recovering keyboard enthusiast" :laughing:

**Comment by yuvadm** [comment]
Welcome to the club :fire:

**Pull request merged**
